server:
  port: 8081
#=========================================
spring:
  rabbitmq:
    host: 121.43.155.2
    port: 5672
    username: guest
    password: guest
  #=========================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.155.2:3307/yeb?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


  redis:
#    超时时间
    timeout: 1000ms
    host: 121.43.155.2
    port: 6379
#    选择数据库
    database: 0
    lettuce:
      pool:
#        最大连接数
        max-active: 1024
#        最大等待时间
        max-wait: 10000ms
#        最大空闲连接
        max-idle: 200
#        最小空闲连接
        min-idle: 5
  #=========================================
#      解决swagger出现循环引用异常，开启循环引用
  main:
    allow-circular-references: true
#    报错Failed to start bean ‘documentationPluginsBootstrapper’解决
#  使用的SpringBoot的版本是2.6.4，因为SpringBoot中SpringMVC的默认策略从ANT_PATH_MATCHER 改成了PATH_PATTERN_PARSER所以就有错误了
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher

#=========================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.wang.pojo
  configuration:
#    开启驼峰命名
    map-underscore-to-camel-case: false

logging:
  level:
    com.wang.mapper: debug
#=========================================

jwt:
#  jwt存储的请求头
  tokenHeader: Authorization
#jwt加解密使用的秘钥
  secret: yeb-secret
#jwt的超期限时间
  expiration: 604800
#jwt负载中拿到开头
  tokenHead: Bearer


